#include "ImageEstimator.h"
#include "ImageBalanceEstimator.h"
#include "ImageDirectEstimator.h"
#include "ImageCutOffEstimator.h"
#include "ImageMaximumEstimator.h"
#include "ImagePowerEstimator.h"
#include "ImageNaiveEstimator.h"